services:
  app:
    image: asolheiro/apicultura
    build: .
    entrypoint: ./entrypoint.sh
    depends_on:
      app-database:
        condition: service_healthy
        restart: true
    env_file:
      - .env
    ports:
      - "8000:8000"
  app-database:
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - type: volume
        source: db-volume
        target: /var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 15s
  test:
    image: postgres
    env_file:
      - .env
    ports:
      - "5433:5432"
volumes:
  db-volume:
    driver: local