name: Pipeline
on: [push , pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      ALGORITHM: ${{ secrets.ALGORITHM }}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}
      POSTGRES_HOST: localhost

    services:
      app-database:
        image: postgres
        env:
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Cópia dos arquivos do repositório 
        uses: actions/checkout@v3

      - name: Instalação do Python:3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalação do Poetry
        run: pipx install poetry
      
      - name: Instalação das dependências
        run: poetry install

      - name: Execução dos testes
        run: poetry run pytest apicultura -vv